package me.jxl.kiosk_satellite.fleet

import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.DataInputStream
import java.io.DataOutputStream
import java.net.DatagramPacket
import java.net.Inet4Address
import java.net.InetAddress
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull
import kotlin.test.assertTrue

class MdnsPacketsTest {
    private val host = "ks-kitchen.local"
    private val address = InetAddress.getByName("192.168.1.5") as Inet4Address

    // Decode the generated bytes independently of the production parser.
    private fun DataInputStream.name(): String {
        val labels = mutableListOf<String>()
        while (true) {
            val size = readUnsignedByte()
            if (size == 0) return labels.joinToString(".")
            assertTrue(size <= 63)
            labels.add(ByteArray(size).also { readFully(it) }.toString(Charsets.UTF_8))
        }
    }

    private fun checkRecords(input: DataInputStream, name: String, ttl: Int, klass: Int) {
        assertEquals(name, input.name())
        assertEquals(1, input.readUnsignedShort())
        assertEquals(klass, input.readUnsignedShort())
        assertEquals(ttl, input.readInt())
        assertEquals(4, input.readUnsignedShort())
        assertContentEquals(address.address, ByteArray(4).also { input.readFully(it) })
        // The address alone: no NSEC, which the Windows resolver would not
        // take (see hostRecords).
    }

    @Test
    fun multicastAnswerHasOneAddressRecordPerHost() {
        val hosts = listOf(host, "ks-identity.local")
        val input = DataInputStream(ByteArrayInputStream(MdnsPackets.buildHostAnswer(hosts, address)))
        assertEquals(0, input.readUnsignedShort())
        assertEquals(0x8400, input.readUnsignedShort())
        assertEquals(0, input.readUnsignedShort())
        assertEquals(2, input.readUnsignedShort())
        assertEquals(0, input.readUnsignedShort())
        assertEquals(0, input.readUnsignedShort())
        hosts.forEach { checkRecords(input, it, 120, 0x8001) }
        assertEquals(0, input.available())
    }

    @Test
    fun legacyIpv6AnswerEchoesQuestionAndIdWithoutCacheFlush() {
        val question = ByteArrayOutputStream().apply {
            val out = DataOutputStream(this)
            host.split('.').forEach { out.writeByte(it.length); out.writeBytes(it) }
            out.writeByte(0)
            out.writeShort(28)
            out.writeShort(1)
        }.toByteArray()
        val reply = MdnsPackets.buildHostAnswer(
            listOf(host), address, qid = 0xbeef, questions = question, qd = 1, legacy = true,
        )
        val input = DataInputStream(ByteArrayInputStream(reply))
        assertEquals(0xbeef, input.readUnsignedShort())
        assertEquals(0x8400, input.readUnsignedShort())
        assertEquals(1, input.readUnsignedShort())
        assertEquals(1, input.readUnsignedShort())
        assertEquals(0, input.readUnsignedShort())
        assertEquals(0, input.readUnsignedShort())
        assertContentEquals(question, ByteArray(question.size).also { input.readFully(it) })
        checkRecords(input, host, 10, 1)
        assertEquals(0, input.available())
    }

    @Test
    fun goodbyeRetractsTheAddressRecord() {
        val reply = MdnsPackets.buildHostAnswer(listOf(host), address, hostTtl = 0)
        val input = DataInputStream(ByteArrayInputStream(reply))
        input.skipBytes(12)
        checkRecords(input, host, 0, 0x8001)
        assertEquals(0, input.available())
    }

    // A compressed A-only answer, as sent by a host with no fleet records.
    // Include a question and place the answer in any of the three sections.
    private fun announcement(
        ip: String = "192.168.1.8",
        name: String = host.uppercase(),
        ttl: Int = 120,
        klass: Int = 0x8001,
        section: Int = 0,
        response: Boolean = true,
    ): DatagramPacket {
        val bytes = ByteArrayOutputStream().apply {
            val out = DataOutputStream(this)
            out.writeShort(0)
            out.writeShort(if (response) 0x8400 else 0)
            out.writeShort(1)
            repeat(3) { out.writeShort(if (it == section) 1 else 0) }
            name.split('.').forEach { out.writeByte(it.length); out.writeBytes(it) }
            out.writeByte(0)
            out.writeShort(1)
            out.writeShort(1)
            out.writeShort(0xc00c)
            out.writeShort(1)
            out.writeShort(klass)
            out.writeInt(ttl)
            out.writeShort(4)
            out.write(InetAddress.getByName(ip).address)
        }.toByteArray()
        // Exercise DNS offsets relative to a DatagramPacket's data slice.
        val padded = ByteArray(7) + bytes + ByteArray(3)
        return DatagramPacket(padded, 7, bytes.size)
    }

    @Test
    fun detectsConflictsWithoutAnyFleetRecordsInEveryResponseSection() {
        repeat(3) { section ->
            assertEquals(
                "192.168.1.8",
                MdnsPackets.conflictingHostAddress(announcement(section = section), host, setOf("192.168.1.5")),
            )
        }
    }

    @Test
    fun ignoresOwnAddressesOnAllInterfacesAndMatchingProxyAnnouncements() {
        val local = setOf("192.168.1.5", "192.168.1.6")
        local.forEach { ip ->
            assertNull(MdnsPackets.conflictingHostAddress(announcement(ip = ip), host, local))
        }
    }

    @Test
    fun ignoresGoodbyesOtherNamesOtherClassesAndQueries() {
        val local = setOf("192.168.1.5")
        listOf(
            announcement(ttl = 0),
            announcement(name = "another.local"),
            announcement(klass = 3),
            announcement(response = false),
        ).forEach { assertNull(MdnsPackets.conflictingHostAddress(it, host, local)) }
        assertNull(MdnsPackets.conflictingHostAddress(announcement(), "", local))
    }

    @Test
    fun rejectsTruncatedRecordsInsteadOfReportingAConflict() {
        val packet = announcement()
        packet.length -= 1
        assertFailsWith<IndexOutOfBoundsException> {
            MdnsPackets.conflictingHostAddress(packet, host, setOf("192.168.1.5"))
        }
    }
}
