import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:kiosk_satellite/managers/wake_word/mww/micro_frontend.dart';

/// Bit-exactness of the Dart microWakeWord frontend against Voice Satellite's
/// JS reference (itself matched to TFLite Micro's C).
///
/// The fixture is generated by scratch/gen_golden.mjs running the real JS
/// frontend. The input is an LCG reproduced exactly below rather than stored:
/// integers and power-of-two divisions only, so both languages agree on every
/// sample without a megabyte of JSON.
///
/// The tables are asserted separately from the features on purpose. They are
/// built with float32 math (Math.fround, log1p) that Dart lacks primitives for,
/// and a single ULP in freqToMel moves a filterbank channel boundary. Caught
/// here that is one obviously-wrong integer; caught only via features it is
/// "detection got slightly worse", which is close to untraceable.
void main() {
  test('PCM16 input matches float input across fragmentation and resets', () {
    final floats = MicroFrontend();
    final pcm = MicroFrontend();
    var seed = 34567;
    for (final size in [0, 1, 159, 160, 161, 479, 480, 481, 1280, 8192]) {
      final samples = Int16List(size);
      for (var i = 0; i < size; i++) {
        seed = (seed * 1103515245 + 12345) & 0x7fffffff;
        samples[i] = switch (i % 5) {
          0 => -32768,
          1 => 32767,
          2 => 0,
          _ => (seed >> 8) & 65535,
        };
      }
      final normalized = [for (final s in samples) s / 32768.0];
      final expected = floats.feed(normalized)
          .map((f) => Float32List.fromList(f)).toList();
      expect(pcm.feedPcm16(samples), expected, reason: '$size PCM samples');
      if (size == 480) {
        floats.reset();
        pcm.reset();
      }
    }
  });

  final fixture = File('test/fixtures/micro_frontend_golden.json');
  final golden = jsonDecode(fixture.readAsStringSync()) as Map<String, dynamic>;

  List<int> ints(Object? v) => (v as List).map((e) => (e as num).toInt()).toList();

  group('derived tables match the JS reference exactly', () {
    final tables = sharedTables();

    test('window coefficients', () {
      expect(tables.windowCoefficients.toList(), ints(golden['windowCoefficients']));
    });

    test('filterbank channel boundaries and weights', () {
      final fb = golden['filterbank'] as Map<String, dynamic>;
      expect(tables.filterbank.startIndex, (fb['startIndex'] as num).toInt());
      expect(tables.filterbank.endIndex, (fb['endIndex'] as num).toInt());
      expect(tables.filterbank.channelFrequencyStarts.toList(),
          ints(fb['channelFrequencyStarts']),
          reason: 'a 1-ULP freqToMel difference shifts these');
      expect(tables.filterbank.channelWeightStarts.toList(),
          ints(fb['channelWeightStarts']));
      expect(tables.filterbank.channelWidths.toList(), ints(fb['channelWidths']));
      expect(tables.filterbank.weights.toList(), ints(fb['weights']));
      expect(tables.filterbank.unweights.toList(), ints(fb['unweights']));
    });

    test('fft plan: factors and twiddles', () {
      final p = golden['fftPlan'] as Map<String, dynamic>;
      expect(tables.fftPlan.nfftReal, (p['nfftReal'] as num).toInt());
      expect(tables.fftPlan.ncfft, (p['ncfft'] as num).toInt());
      expect(tables.fftPlan.factors, ints(p['factors']));
      expect(tables.fftPlan.twCos.toList(), ints(p['twCos']));
      expect(tables.fftPlan.twSin.toList(), ints(p['twSin']));
      expect(tables.fftPlan.stCos.toList(), ints(p['stCos']));
      expect(tables.fftPlan.stSin.toList(), ints(p['stSin']));
    });

    test('pcan gain lut', () {
      // Its a2 coefficients are negative, which is exactly where JS's
      // Math.floor and Dart's ~/ disagree. See _floorDiv.
      expect(tables.gainLut.toList(), ints(golden['gainLut']));
    });
  });

  test('roundBankers matches JS for negative halves', () {
    // Dart's .round() rounds halves away from zero and would fail every
    // negative case here. Quantization's zero_point is -128, so this is the
    // common path, not a corner.
    for (final pair in golden['roundBankers'] as List) {
      final x = ((pair as List)[0] as num).toDouble();
      final expected = (pair[1] as num).toInt();
      expect(roundBankers(x), expected, reason: 'roundBankers($x)');
    }
  });

  group('feature frames match the JS reference exactly', () {
    /// The same LCG gen_golden.mjs uses: Math.imul(seed, 1103515245) + 12345,
    /// unsigned 32-bit.
    List<double> lcgInput(int n) {
      var seed = 12345;
      final out = <double>[];
      for (var i = 0; i < n; i++) {
        seed = ((seed * 1103515245) + 12345) & 0xFFFFFFFF;
        out.add(((seed % 65536) - 32768) / 32768);
      }
      return out;
    }

    test('48 frames of 40 features, bit-identical', () {
      final meta = golden['meta'] as Map<String, dynamic>;
      final samples = (meta['samples'] as num).toInt();
      final expected = (golden['frames'] as List)
          .map((f) => (f as List).map((e) => (e as num).toDouble()).toList())
          .toList();

      final input = lcgInput(samples);
      final frontend = MicroFrontend();
      final frames = <List<double>>[];
      for (var off = 0; off < samples; off += 160) {
        for (final f in frontend.feed(input.sublist(off, off + 160))) {
          frames.add(f.toList());
        }
      }

      expect(frames.length, expected.length);
      for (var i = 0; i < frames.length; i++) {
        expect(frames[i], expected[i], reason: 'frame $i diverges');
      }
    });
  });

  test('full-scale negative clipping does not crash the frontend', () {
    // A -1.0 sample quantizes to -32768; under the window's peak 4096
    // coefficient the windowed value is -32768 again, whose MSB is 16 and the
    // raw input shift is -1. Dart throws on negative shifts (issue #52), so
    // the shift is clamped to 0. Feed enough clipped windows to guarantee the
    // peak coefficient meets a full-scale sample.
    final frontend = MicroFrontend();
    final clipped = List<double>.filled(160, -1.0);
    final frames = <List<double>>[];
    for (var chunk = 0; chunk < 10; chunk++) {
      for (final f in frontend.feed(clipped)) {
        frames.add(f.toList());
      }
    }
    expect(frames, isNotEmpty);
    for (final frame in frames) {
      expect(frame.every((v) => v.isFinite), isTrue);
    }
  });
}
